import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Aside from "@/components/aside/Aside";
import Header from "@/components/header/Header";

const roboto = Roboto({ weight : ["100","300","400","500","700","900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          roboto.className,
          "bg-body flex flex-col md:flex-row"
        )}
      >
        <Aside/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
